name: Compile CSS

on:
  push:
  pull_request:

env:
  NODE: 14

jobs:
  css:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"

      - name: Install Yarn & Gulp.js
        run: npm install -g yarn gulp-cli

      - name: Install dependencies
        run: yarn install

      - name: Compile CSS with Gulp.js
        run: gulp compile